{% set name = "qh3" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qh3-{{ version }}.tar.gz
  sha256: ca3eefb44224ebb5f950beeef58fb8178779ab604252eeea1788407ad37daa47

build:
  skip: true  # [py<37]
  script:
    - export OPENSSL_DIR=$PREFIX  # [osx]
    - export AWS_LC_SYS_CMAKE_BUILDER=1
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nasm  # [win]
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
    - openssl  # [osx]
    - clangdev  # [linux]
  run:
    - python

test:
  imports:
    - qh3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/qh3
  summary: A lightway and fast implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
