{% set name = "qh3" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qh3-{{ version }}.tar.gz
  sha256: 8f46957590f4cd0ef8c39ee0e71a2c1ca7daaa6b43447354b99545f2159cab90

build:
  skip: true  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - export OPENSSL_DIR=$PREFIX  # [osx]
    - export AWS_LC_SYS_CMAKE_BUILDER=1
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nasm  # [win]
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
    - openssl  # [osx]
    - clangdev  # [linux]
  run:
    - python

test:
  imports:
    - qh3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/qh3
  summary: A lightway and fast implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
