{% set name = "qh3" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qh3-{{ version }}.tar.gz
  sha256: 3d2e1616023286373ab40a276cbf0b8960e6bda640bca0569495dad57775f6b8
  patches:
    - 0001-Patch-aws-lc-sys.patch  # [unix]

build:
  skip: true  # [py<37]
  script:
    - cargo patch  # [unix]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - export OPENSSL_DIR=$PREFIX  # [osx]
    - export AWS_LC_SYS_CMAKE_BUILDER=1
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - maturin >=1.2,<2.0                     # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - make
    - nasm  # [win]
    - cargo-bundle-licenses
    - cargo-patch  # [unix]
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
    - openssl  # [osx]
    - clangdev  # [linux]
  run:
    - python

test:
  imports:
    - qh3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/qh3
  summary: A lightway and fast implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
