schema_version: 1

context:
  name: qh3
  version: "1.9.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/qh3-${{ version }}.tar.gz
  sha256: c6c92f63c2ec292256b5a5ed9345c42344bdaca2e55ec795623987a563aea19c

build:
  number: 0
  script:
    env:
      OPENSSL_DIR: $PREFIX
      AWS_LC_SYS_CMAKE_BUILDER: '1'
    content:
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - maturin >=1.2,<2.0
        - cross-python_${{ target_platform }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - cmake
    - make
    - cargo-bundle-licenses
    - if: win
      then: nasm
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
    - if: linux
      then: clangdev
    - if: osx
      then: openssl
  run:
    - python

tests:
  - python:
      imports:
        - qh3
      pip_check: true

about:
  summary: A lightway and fast implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/jawah/qh3

extra:
  recipe-maintainers:
    - thewchan
